# kvstore.conf - example configuration for kvstore-server

# TCP port the server will listen on.
# If omitted, kvstore-server defaults to 2000.
port 2000

############################################
# 持久化总开关
############################################

# 是否启用持久化（RDB + AOF）
# 支持：1/0 或 yes/no
enable_persistence yes

############################################
# Redis 风格持久化（RDB + AOF）
############################################

# RDB 文件目录与文件名
dir log
dbfilename dump.rdb

# RDB 自动保存策略：save <seconds> <changes>
# 注：写 "save \"\"" 可禁用 RDB 自动保存
# save ""
save 900 1
save 300 10
save 60 10000

# AOF 开关与策略
appendonly yes
appendfilename appendonly.aof
appendfsync everysec  # always / everysec / no


# network_backend reactor proactor ntyco
network_backend reactor

############################################

